import { Car } from '../interfaces/Car';

export const CARS: Car[] = [
  {
    name: 'Pagani Huayra',
    price: '$256 /Hour',
    image: '/pagani.png',
    modelUrl: '/car.glb',
    properties: [
      { label: 'Modelo', value: 'Pagani Huayra' },
      { label: 'Motor', value: 'V12 Biturbo de 6.0 litros' },
      { label: 'Potência', value: '730 cv' },
      { label: 'Torque', value: '1000 Nm' },
      { label: 'Velocidade Máxima', value: '370 km/h' },
      { label: 'Aceleração (0-100 km/h)', value: '3.3 segundos' },
      { label: 'Ano', value: '2012' },
      { label: 'Assentos', value: '2' },
      { label: 'Portas', value: '2' },
      { label: 'Passageiros', value: '2' },
      { label: 'Combustível', value: 'Petrol' },
      { label: 'Quilometragem', value: 'N/A' }
    ],
    rating: 4.8,
    reviews: 1200,
  },
  {
    name: '1972 Datsun 240k GT',
    price: '$300 /Hour',
    image: '/Datsun.png',
    modelUrl: '/datsun.glb',
    properties: [
      { label: 'Modelo', value: '1972 Datsun 240k GT' },
      { label: 'Motor', value: 'V12 de 6.5 litros' },
      { label: 'Potência', value: '770 cv' },
      { label: 'Torque', value: '720 Nm' },
      { label: 'Velocidade Máxima', value: '350 km/h' },
      { label: 'Aceleração (0-100 km/h)', value: '2.9 segundos' },
      { label: 'Ano', value: '1972' },
      { label: 'Assentos', value: '2' },
      { label: 'Portas', value: '2' },
      { label: 'Passageiros', value: '2' },
      { label: 'Combustível', value: 'Petrol' },
      { label: 'Quilometragem', value: 'N/A' }
    ],
    rating: 4.5,
    reviews: 850,
  },
  {
    name: '1967 Shelby GT500',
    price: '$240 /Hour',
    image: '/Shelby.png',
    modelUrl: '/shelby.glb',
    properties: [
      { label: 'Modelo', value: '1967 Shelby GT500' },
      { label: 'Motor', value: 'V8 5.8 litros (Aproximado)' },
      { label: 'Potência', value: '750 cv (Aproximado)' },
      { label: 'Torque', value: '880 Nm (Aproximado)' },
      { label: 'Velocidade Máxima', value: '320 km/h (Aproximado)' },
      { label: 'Aceleração (0-100 km/h)', value: '3.5 segundos (Aproximado)' },
      { label: 'Ano', value: '1967' },
      { label: 'Assentos', value: '4' },
      { label: 'Portas', value: '2' },
      { label: 'Passageiros', value: '4' },
      { label: 'Combustível', value: 'Petrol' },
      { label: 'Quilometragem', value: 'N/A' }
    ],
    rating: 4.7,
    reviews: 980,
  },
  {
    name: 'Ford Mustang Shelby GT500KR',
    price: '$240 /Hour',
    image: '/ford_mustang_shelby_gt500kr.png',
    modelUrl: '/ford_mustang_shelby_gt500kr.glb',
    properties: [
      { label: 'Modelo', value: 'Ford Mustang Shelby GT500KR' },
      { label: 'Motor', value: 'V8 5.8 litros (Aproximado)' },
      { label: 'Potência', value: '750 cv (Aproximado)' },
      { label: 'Torque', value: '880 Nm (Aproximado)' },
      { label: 'Velocidade Máxima', value: '320 km/h (Aproximado)' },
      { label: 'Aceleração (0-100 km/h)', value: '3.5 segundos (Aproximado)' },
      { label: 'Ano', value: '2008' },
      { label: 'Assentos', value: '4' },
      { label: 'Portas', value: '2' },
      { label: 'Passageiros', value: '4' },
      { label: 'Combustível', value: 'Petrol' },
      { label: 'Quilometragem', value: 'N/A' }
    ],
    rating: 4.6,
    reviews: 1100,
  },
  {
    name: 'Chevrolet Impala 1967 (Supernatural Edition)',
    price: '$350 /Day',
    image: '/chevrolet_impala_1967_supernatural.png',
    modelUrl: '/chevrolet_impala_1967_supernatural.glb',
    properties: [
      { label: 'Modelo', value: 'Chevrolet Impala 1967' },
      { label: 'Apelido', value: 'Baby (Supernatural)' },
      { label: 'Motor', value: 'V8 Big Block 327 ou 427 cu in (Original)' },
      { label: 'Potência', value: '275 - 385 cv (Original, dependendo do motor)' },
      { label: 'Transmissão', value: 'Manual 4 marchas / Automática (Original)' },
      { label: 'Ano', value: '1967' },
      { label: 'Assentos', value: '5' },
      { label: 'Portas', value: '2' },
      { label: 'Passageiros', value: '5' },
      { label: 'Combustível', value: 'Petrol' },
      { label: 'Quilometragem', value: 'N/A' },
      { label: 'Destaques', value: 'Aura sobrenatural, porta-malas espaçoso para caça' }
    ],
    rating: 5.0,
    reviews: 500,
  },
  {
    name: 'Máquina Misteriosa (Estilo Esportivo)',
    price: '$180 /Hour',
    image: '/mystery_machine_sport.png',
    modelUrl: '/mystery_machine_sport.glb',
    properties: [
      { label: 'Modelo Base', value: 'Van Customizada (Inspirada em Geração Pós-60s)' },
      { label: 'Estilo', value: 'Hot Rod / Tuning Esportivo' },
      { label: 'Motor', value: 'V6 Turbo Otimizado (Ficcional)' },
      { label: 'Potência', value: '350 cv (Estimado, para performance esportiva)' },
      { label: 'Ano', value: '1970' },
      { label: 'Assentos', value: '4' },
      { label: 'Portas', value: '3' },
      { label: 'Passageiros', value: '4' },
      { label: 'Combustível', value: 'Electric' },
      { label: 'Quilometragem', value: '400 Km' }
    ],
    rating: 4.3,
    reviews: 150,
  }
];